/*
Problem:
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Link: https://leetcode.com/problems/find-the-difference/

Solution:
We can xor the values of both strings
*/

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        char extraCharacter = t.charAt(s.length());

        for (int i = 0; i < s.length(); i++) {
            extraCharacter ^= s.charAt(i);
            extraCharacter ^= t.charAt(i);
        }

        return extraCharacter;
    }

    public char findTheDifference_(String s, String t) {
        int sValue = 0;
        int tValue = t.charAt(s.length());
        
        for(int i = 0; i < s.length(); i++) {
            sValue += (int)s.charAt(i);
            tValue += (int)t.charAt(i);
        }
        
        return (char)(tValue - sValue);
    }
}